#!/usr/bin/env bash
#
# install-guardrails.sh — install local commit/push guardrails for this repo.
#
# This script is generic and contains NO personal data. It reads optional
# machine-local config, if present, from:
#
#   ~/.config/oss-guard/git-identity       public commit identity to use
#                                           (GIT_USER_NAME / GIT_USER_EMAIL lines)
#   ~/.config/oss-guard/deny-patterns.txt   personal-identifier denylist,
#                                           one fixed string per line, '#' comments
#
# Neither file is part of this repository. Outside contributors who do not have
# these files still get working gitleaks-based hooks (with a warning); the
# denylist checks simply become no-ops for them.
#
# Run once after cloning:   scripts/install-guardrails.sh
#
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$(cd "$REPO_ROOT" && git rev-parse --git-path hooks)"
CONFIG_DIR="${OSS_GUARD_DIR:-$HOME/.config/oss-guard}"
IDENTITY_FILE="$CONFIG_DIR/git-identity"

mkdir -p "$HOOKS_DIR"

# ---------------------------------------------------------------------------
# 1. Commit identity
# ---------------------------------------------------------------------------
if [ -f "$IDENTITY_FILE" ]; then
  # Parse KEY=VALUE lines directly (values may contain spaces; do not source).
  GIT_USER_NAME="$(grep -E '^GIT_USER_NAME=' "$IDENTITY_FILE" | head -1 | cut -d= -f2-)"
  GIT_USER_EMAIL="$(grep -E '^GIT_USER_EMAIL=' "$IDENTITY_FILE" | head -1 | cut -d= -f2-)"
  if [ -n "${GIT_USER_NAME:-}" ] && [ -n "${GIT_USER_EMAIL:-}" ]; then
    git -C "$REPO_ROOT" config user.name "$GIT_USER_NAME"
    git -C "$REPO_ROOT" config user.email "$GIT_USER_EMAIL"
    echo "guardrails: commit identity set to $GIT_USER_NAME <$GIT_USER_EMAIL>"
  else
    echo "guardrails: WARNING $IDENTITY_FILE present but incomplete; leaving git identity unchanged." >&2
  fi
else
  echo "guardrails: WARNING no $IDENTITY_FILE; leaving git identity unchanged (use a GitHub noreply email for commits)." >&2
fi

# ---------------------------------------------------------------------------
# 2. pre-commit hook
# ---------------------------------------------------------------------------
cat > "$HOOKS_DIR/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Local guardrail (generated by scripts/install-guardrails.sh — do not edit).
set -euo pipefail

CONFIG_DIR="${OSS_GUARD_DIR:-$HOME/.config/oss-guard}"
DENY="$CONFIG_DIR/deny-patterns.txt"

# Local-only overlay paths that must never be committed (belt-and-braces
# against `git add -f`). Directory entries end with '/'.
OVERLAY_PATHS='ASC.md
PROGRESS.md
Config/ExportOptions.AppStore.plist
marketing/
docs/assets/app-icon-options/
docs/specs/SPEC-oss-publication.md
private/'

fail() { echo "pre-commit BLOCKED: $*" >&2; exit 1; }

patterns() { grep -v '^[[:space:]]*#' "$DENY" | grep -v '^[[:space:]]*$'; }

# 1. Block a personal commit email leaking through global config.
email="$(git config user.email 2>/dev/null || true)"
if [ -f "$DENY" ] && [ -n "$email" ]; then
  if printf '%s\n' "$email" | grep -iFf <(patterns) >/dev/null 2>&1; then
    fail "commit email '$email' matches a denylist entry"
  fi
fi

# 2. gitleaks over staged changes.
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks git --pre-commit --staged --no-banner \
    || fail "gitleaks found a potential secret in staged changes"
else
  echo "pre-commit: WARNING gitleaks not installed; skipping secret scan" >&2
fi

staged_files="$(git diff --cached --name-only --diff-filter=ACMR)"

# 3. Denylist over staged file paths and staged added lines.
if [ -f "$DENY" ]; then
  if [ -n "$staged_files" ] \
     && printf '%s\n' "$staged_files" | grep -iFf <(patterns) >/dev/null 2>&1; then
    hit="$(printf '%s\n' "$staged_files" | grep -iFf <(patterns) | head -1)"
    fail "staged file path matches the denylist: $hit"
  fi
  added="$(git diff --cached --diff-filter=ACMR -U0 \
           | grep -E '^\+' | grep -Ev '^\+\+\+' || true)"
  if [ -n "$added" ] \
     && printf '%s\n' "$added" | grep -iFf <(patterns) >/dev/null 2>&1; then
    pat="$(printf '%s\n' "$added" | grep -ioFf <(patterns) | head -1)"
    fail "a staged added line matches the denylist (pattern: $pat)"
  fi
else
  echo "pre-commit: WARNING no $DENY; running in gitleaks-only mode" >&2
fi

# 4. Overlay/private path guard.
if [ -n "$staged_files" ]; then
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    while IFS= read -r p; do
      [ -z "$p" ] && continue
      case "$p" in
        */) [ "${f#"$p"}" != "$f" ] && fail "staged path '$f' is a local-only overlay path" ;;
        *)  [ "$f" = "$p" ] && fail "staged path '$f' is a local-only overlay path" ;;
      esac
    done <<OVL
$OVERLAY_PATHS
OVL
  done <<FILES
$staged_files
FILES
fi

exit 0
HOOK
chmod +x "$HOOKS_DIR/pre-commit"

# ---------------------------------------------------------------------------
# 3. pre-push hook
# ---------------------------------------------------------------------------
cat > "$HOOKS_DIR/pre-push" <<'HOOK'
#!/usr/bin/env bash
# Local guardrail (generated by scripts/install-guardrails.sh — do not edit).
set -euo pipefail

CONFIG_DIR="${OSS_GUARD_DIR:-$HOME/.config/oss-guard}"
DENY="$CONFIG_DIR/deny-patterns.txt"
ZERO="0000000000000000000000000000000000000000"

fail() { echo "pre-push BLOCKED: $*" >&2; exit 1; }
patterns() { grep -v '^[[:space:]]*#' "$DENY" | grep -v '^[[:space:]]*$'; }

while read -r _local_ref local_sha _remote_ref remote_sha; do
  [ "$local_sha" = "$ZERO" ] && continue   # branch deletion
  if [ "$remote_sha" = "$ZERO" ]; then
    range="$local_sha"                     # new ref: scan all reachable
  else
    range="$remote_sha..$local_sha"
  fi

  if command -v gitleaks >/dev/null 2>&1; then
    gitleaks git --no-banner --log-opts="$range" . \
      || fail "gitleaks found a potential secret in outgoing commits ($range)"
  fi

  if [ -f "$DENY" ]; then
    added="$(git diff "$range" -U0 | grep -E '^\+' | grep -Ev '^\+\+\+' || true)"
    if [ -n "$added" ] \
       && printf '%s\n' "$added" | grep -iFf <(patterns) >/dev/null 2>&1; then
      pat="$(printf '%s\n' "$added" | grep -ioFf <(patterns) | head -1)"
      fail "an outgoing added line matches the denylist (pattern: $pat, range: $range)"
    fi
  fi
done

exit 0
HOOK
chmod +x "$HOOKS_DIR/pre-push"

echo "guardrails: installed pre-commit and pre-push hooks in $HOOKS_DIR"
